-- This file is generated by SWIG. Please do *not* modify by hand.
--
with c_math_c;
with c_math_c.Vector_3;
with Interfaces.C;

package bullet_c.ray_Collision is

   -- Item
   --

   type Item is record
      near_Object  : access bullet_c.Object;
      hit_Fraction : aliased c_math_c.Real;
      Normal_world : aliased c_math_c.Vector_3.Item;
      Site_world   : aliased c_math_c.Vector_3.Item;
   end record;

   -- Items
   --
   type Items is
     array
       (Interfaces.C.size_t range <>) of aliased bullet_c.ray_Collision.Item;

   -- Pointer
   --
   type Pointer is access all bullet_c.ray_Collision.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased bullet_c.ray_Collision.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all bullet_c.ray_Collision.Pointer;

   function construct return bullet_c.ray_Collision.Item;

private

   pragma Import (C, construct, "Ada_new_ray_Collision");

end bullet_c.ray_Collision;
