-- This file is generated by SWIG. Please do *not* modify by hand.
--
with bullet_c.Pointers;

package bullet_c.pointer_Pointers
is

   -- Shape_Pointer_Pointer
   --
   type Shape_Pointer_Pointer is access all bullet_c.Pointers.Shape_Pointer;

   -- Object_Pointer_Pointer
   --
   type Object_Pointer_Pointer is access all bullet_c.Pointers.Object_Pointer;

   -- Joint_Pointer_Pointer
   --
   type Joint_Pointer_Pointer is access all bullet_c.Pointers.Joint_Pointer;

   -- Space_Pointer_Pointer
   --
   type Space_Pointer_Pointer is access all bullet_c.Pointers.Space_Pointer;

end bullet_c.pointer_Pointers;
