-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;

package bullet_c.Pointers is

   -- Shape_Pointer
   --
   type Shape_Pointer is access all bullet_c.Shape;

   -- Shape_Pointers
   --
   type Shape_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased bullet_c.Pointers.Shape_Pointer;

   -- Object_Pointer
   --
   type Object_Pointer is access all bullet_c.Object;

   -- Object_Pointers
   --
   type Object_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased bullet_c.Pointers.Object_Pointer;

   -- Joint_Pointer
   --
   type Joint_Pointer is access all bullet_c.Joint;

   -- Joint_Pointers
   --
   type Joint_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased bullet_c.Pointers.Joint_Pointer;

   -- Space_Pointer
   --
   type Space_Pointer is access all bullet_c.Space;

   -- Space_Pointers
   --
   type Space_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased bullet_c.Pointers.Space_Pointer;

end bullet_c.Pointers;
