-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Swig;
with Interfaces.C;

package bullet_c is

   -- Shape
   --
   subtype Shape is Swig.opaque_structure;

   type Shape_array is
     array (Interfaces.C.size_t range <>) of aliased bullet_c.Shape;

   -- Object
   --
   subtype Object is Swig.opaque_structure;

   type Object_array is
     array (Interfaces.C.size_t range <>) of aliased bullet_c.Object;

   -- Joint
   --
   subtype Joint is Swig.opaque_structure;

   type Joint_array is
     array (Interfaces.C.size_t range <>) of aliased bullet_c.Joint;

   -- Space
   --
   subtype Space is Swig.opaque_structure;

   type Space_array is
     array (Interfaces.C.size_t range <>) of aliased bullet_c.Space;

end bullet_c;
