name        = "lace_xml"
description = "Provides simple XML read/write support."
version     = "0.0.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/xml.gpr"]

[[depends-on]]     # Added by alr
lace_shared = "*"  # Added by alr
