-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;

package c_math_c.Pointers is

   -- Real_Pointer
   --
   type Real_Pointer is access all c_math_c.Real;

   -- Real_Pointers
   --
   type Real_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased c_math_c.Pointers.Real_Pointer;

   -- Index_Pointer
   --
   type Index_Pointer is access all c_math_c.Index;

   -- Index_Pointers
   --
   type Index_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased c_math_c.Pointers.Index_Pointer;

end c_math_c.Pointers;
