-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package c_math_c is

   -- Real
   --
   subtype Real is Interfaces.C.C_float;

   type Real_array is
     array (Interfaces.C.size_t range <>) of aliased c_math_c.Real;

end c_math_c;
