-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package c_math_c.Pointers is

   -- Real_Pointer
   --
   type Real_Pointer is access all c_math_c.Real;

   -- Real_Pointers
   --
   type Real_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased c_math_c.Pointers.Real_Pointer;

end c_math_c.Pointers;
