-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;

package c_math_c.Triangle is

   -- Item
   --

   type Item is record
      a : aliased c_math_c.Index;
      b : aliased c_math_c.Index;
      c : aliased c_math_c.Index;
   end record;

   -- Items
   --
   type Items is
     array (Interfaces.C.size_t range <>) of aliased c_math_c.Triangle.Item;

   -- Pointer
   --
   type Pointer is access all c_math_c.Triangle.Item;

   -- Pointers
   --
   type Pointers is
     array (Interfaces.C.size_t range <>) of aliased c_math_c.Triangle.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all c_math_c.Triangle.Pointer;

   function construct return c_math_c.Triangle.Item;

   function construct
     (a : in c_math_c.Real;
      b : in c_math_c.Real;
      c : in c_math_c.Real) return c_math_c.Triangle.Item;

private

   function construct_v1 return c_math_c.Triangle.Item;

   function construct return c_math_c.Triangle.Item renames construct_v1;

   pragma Import (C, construct_v1, "Ada_new_Triangle__SWIG_0");

   function construct_v2
     (a : in c_math_c.Real;
      b : in c_math_c.Real;
      c : in c_math_c.Real) return c_math_c.Triangle.Item;

   function construct
     (a : in c_math_c.Real;
      b : in c_math_c.Real;
      c : in c_math_c.Real) return c_math_c.Triangle.Item renames
     construct_v2;

   pragma Import (C, construct_v2, "Ada_new_Triangle__SWIG_1");

end c_math_c.Triangle;
