-- This file is generated by SWIG. Please do *not* modify by hand.
--
with c_math_c.Pointers;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package c_math_c.pointer_Pointers is

   -- Real_Pointer_Pointer
   --
   type Real_Pointer_Pointer is access all c_math_c.Pointers.Real_Pointer;

end c_math_c.pointer_Pointers;
