name        = "lace_c_math"
description = "A binding to the C math code used by box2d & bullet bindings."
version     = "0.0.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/c_math_thin.gpr"]

[[depends-on]]   # Added by alr
lace_math = "*"  # Added by alr
lace_swig = "*"  # Added by alr
