name        = "lace_c_math"
description = "A binding to the C math code used by box2d & bullet bindings."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/c_math_thin.gpr"]

[[depends-on]]
lace_math = "~0.1"
lace_swig = "~0.1"
