name        = "lace_opengl"
description = "Provides an openGL engine."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/opengl.gpr"]

[[depends-on]]
lace_collada = "~0.1"
