name        = "lace_opengl"
description = "Provides an openGL engine."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/opengl.gpr"]

[[depends-on]]
lace_collada = "~0.1"

[depends-on."case(os)"."linux|windows"]
libfreetype = "^2"

[gpr-set-externals."case(os)"]
"linux|macos" = {FreeType_Linker_Param = "-lfreetype"}
"windows"     = {FreeType_Linker_Param = "-lfreetype-6"}
