-- This file is generated by SWIG. Please do *not* modify by hand.
--
with box2d_c.Pointers;



package box2d_c.pointer_Pointers
is

   -- Shape_Pointer_Pointer
   --
   type Shape_Pointer_Pointer is access all box2d_c.Pointers.Shape_Pointer;



   -- Object_Pointer_Pointer
   --
   type Object_Pointer_Pointer is access all box2d_c.Pointers.Object_Pointer;



   -- Joint_Pointer_Pointer
   --
   type Joint_Pointer_Pointer is access all box2d_c.Pointers.Joint_Pointer;



   -- Space_Pointer_Pointer
   --
   type Space_Pointer_Pointer is access all box2d_c.Pointers.Space_Pointer;



   -- b2Joint_Pointer_Pointer
   --
   type b2Joint_Pointer_Pointer is access all box2d_c.Pointers.b2Joint_Pointer;


end box2d_c.pointer_Pointers;
