-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Swig;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package box2d_c is

   -- Shape
   --
   subtype Shape is Swig.opaque_structure;

   type Shape_array is
     array (Interfaces.C.size_t range <>) of aliased box2d_c.Shape;

   -- Object
   --
   subtype Object is Swig.opaque_structure;

   type Object_array is
     array (Interfaces.C.size_t range <>) of aliased box2d_c.Object;

   -- Joint
   --
   subtype Joint is Swig.opaque_structure;

   type Joint_array is
     array (Interfaces.C.size_t range <>) of aliased box2d_c.Joint;

   -- Space
   --
   subtype Space is Swig.opaque_structure;

   type Space_array is
     array (Interfaces.C.size_t range <>) of aliased box2d_c.Space;

   -- b2Joint
   --
   subtype b2Joint is Swig.opaque_structure;

   type b2Joint_array is
     array (Interfaces.C.size_t range <>) of aliased box2d_c.b2Joint;

end box2d_c;
