-- This file is generated by SWIG. Please do *not* modify by hand.
--
with c_math_c.Vector_3;
with interfaces.C;



package box2d_c.b2d_Contact is

   -- Item
   --

type Item is
      record
         Object_A : access box2d_c.Object;
         Object_B : access box2d_c.Object;
         Site : aliased c_math_c.Vector_3.Item;
      end record;



   -- Items
   --
   type Items is array (interfaces.C.Size_t range <>) of aliased box2d_c.b2d_Contact.Item;



   -- Pointer
   --
   type Pointer is access all box2d_c.b2d_Contact.Item;

   -- Pointers
   --
   type Pointers is array (interfaces.C.Size_t range <>) of aliased box2d_c.b2d_Contact.Pointer;



   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all box2d_c.b2d_Contact.Pointer;






   function  construct  return box2d_c.b2d_Contact.Item;









private



   pragma Import (C, construct, "Ada_new_b2d_Contact");



end box2d_c.b2d_Contact;
