name        = "lace_collada"
description = "A Collada parser."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/collada.gpr"]

[[depends-on]]
lace_math = "~0.1"
lace_xml  = "~0.1"
