-- This file is generated by SWIG. Please do *not* modify by hand.
--
with osmesa_c.Pointers;
with Interfaces.C;

package osmesa_c.pointer_Pointers is

   -- GLenum_Pointer_Pointer
   --
   type GLenum_Pointer_Pointer is access all osmesa_c.Pointers.GLenum_Pointer;

   -- GLint_Pointer_Pointer
   --
   type GLint_Pointer_Pointer is access all osmesa_c.Pointers.GLint_Pointer;

   -- GLsizei_Pointer_Pointer
   --
   type GLsizei_Pointer_Pointer is
     access all osmesa_c.Pointers.GLsizei_Pointer;

   -- GLboolean_Pointer_Pointer
   --
   type GLboolean_Pointer_Pointer is
     access all osmesa_c.Pointers.GLboolean_Pointer;

   -- OSMesaContext_Pointer_Pointer
   --
   type OSMesaContext_Pointer_Pointer is
     access all osmesa_c.Pointers.OSMesaContext_Pointer;

   -- OSMESAproc_Pointer_Pointer
   --
   type OSMESAproc_Pointer_Pointer is
     access all osmesa_c.Pointers.OSMESAproc_Pointer;

end osmesa_c.pointer_Pointers;
