-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Swig;
with Interfaces.C;

package osmesa_c is

   -- GLenum
   --
   subtype GLenum is Interfaces.C.unsigned;

   type GLenum_array is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.GLenum;

   -- GLint
   --
   subtype GLint is Interfaces.C.int;

   type GLint_array is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.GLint;

   -- GLsizei
   --
   subtype GLsizei is Interfaces.C.int;

   type GLsizei_array is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.GLsizei;

   -- GLboolean
   --
   subtype GLboolean is Interfaces.C.unsigned_char;

   type GLboolean_array is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.GLboolean;

   -- OSMesaContext
   --
   subtype OSMesaContext is Swig.opaque_structure;

   type OSMesaContext_array is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.OSMesaContext;

   -- OSMESAproc
   --
   type OSMESAproc is access
 procedure;
   pragma Convention (C, OSMESAproc);

   -- OSMESAprocs
   --
   type OSMESAprocs is
     array (Interfaces.C.size_t range <>) of aliased osmesa_c.OSMESAproc;

   OSMESA_MAJOR_VERSION         : constant := 11;
   OSMESA_MINOR_VERSION         : constant := 2;
   OSMESA_PATCH_VERSION         : constant := 0;
   OSMESA_BGRA                  : constant := 16#1#;
   OSMESA_ARGB                  : constant := 16#2#;
   OSMESA_BGR                   : constant := 16#4#;
   OSMESA_RGB_565               : constant := 16#5#;
   OSMESA_ROW_LENGTH            : constant := 16#10#;
   OSMESA_Y_UP                  : constant := 16#11#;
   OSMESA_WIDTH                 : constant := 16#20#;
   OSMESA_HEIGHT                : constant := 16#21#;
   OSMESA_FORMAT                : constant := 16#22#;
   OSMESA_TYPE                  : constant := 16#23#;
   OSMESA_MAX_WIDTH             : constant := 16#24#;
   OSMESA_MAX_HEIGHT            : constant := 16#25#;
   OSMESA_DEPTH_BITS            : constant := 16#30#;
   OSMESA_STENCIL_BITS          : constant := 16#31#;
   OSMESA_ACCUM_BITS            : constant := 16#32#;
   OSMESA_PROFILE               : constant := 16#33#;
   OSMESA_CORE_PROFILE          : constant := 16#34#;
   OSMESA_COMPAT_PROFILE        : constant := 16#35#;
   OSMESA_CONTEXT_MAJOR_VERSION : constant := 16#36#;
   OSMESA_CONTEXT_MINOR_VERSION : constant := 16#37#;

end osmesa_c;
