name        = "lace_gel_full_demo"
description = "A demo of most of GEL's features."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

executables = ["launch_full_demo"]

project-files = ["full_demo.gpr"]

[[depends-on]]
lace_gel = "~0.1"
