name        = "lace_gel"
description = "A 2D/3D game engine library (GEL)."
version     = "0.1.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

project-files = ["library/gel.gpr"]

[[depends-on]]
lace_opengl  = "~0.1"
lace_physics = "~0.1"
sdlada       = "2.3.1"
