name        = "lace"
description = "Contains a set of low level re-usable Ada components."
version     = "0.0.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"

long-description = "\nContains:\n\n   - lace.Events    : Provides a 'subject/oberver' 'event/response' facility.\n   - lace.Any       : Provides an interface to allow heterogenous containers.\n   - lace.fast_Pool : Provides a generic which allows fast allocation/deallocation.\n   - lace.Text      : Provides a DSA friendly set of text operations.\n\n"

project-files = ["library/lace.gpr"]

[[depends-on]]     # Added by alr
lace_shared = "*"  # Added by alr

[[pins]]
lace_shared = { path = "../../0-floor/lace_shared" }
